version: '3'

dotenv: ['.env', '../.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  up:
    goose postgres $DATABASE_URL up

  down:
    goose postgres $DATABASE_URL down

  status:
    goose postgres $DATABASE_URL status